apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dot-ai
resources:
  - ../../base
images:
  - name: ghcr.io/vfarcic/dot-ai-website
    newTag: "0.3.37"
replicas:
  - name: dot-ai-website
    count: 1
