apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dot-ai-website-tls
  labels:
    dot-ai.io/managed: "true"
    dot-ai.io/app-name: dot-ai-website
spec:
  secretName: dot-ai-website-tls-secret
  duration: 2160h
  renewBefore: 360h
  commonName: devopstoolkit.ai
  dnsNames:
  - devopstoolkit.ai
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
