apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dot-ai-website
  labels:
    dot-ai.io/managed: "true"
    dot-ai.io/app-name: dot-ai-website
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - devopstoolkit.ai
    secretName: dot-ai-website-tls-secret
  rules:
  - host: devopstoolkit.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dot-ai-website
            port:
              number: 80
